// Generated by CoffeeScript 1.3.3
(function() {
  var google_calendar,
    _this = this;

  google_calendar = require('../calendar-api.js.coffee');

  exports.index = function(req, res) {
    return google_calendar.getCalendarList(req.session.auth_token, function(result) {
      var calendarList;
      calendarList = result && result.items ? result.items : result;
      return res.render('index', {
        title: 'Express',
        calendars: calendarList
      });
    });
  };

  exports.events = function(req, res) {
    return google_calendar.getCalendarItems(req.session.auth_token, req.query.calendarId, function(result) {
      var eventList;
      console.log(result);
      eventList = result && result.items ? result.items : result;
      return res.render('events', {
        title: 'Express',
        events: eventList
      });
    });
  };

}).call(this);
