// Generated by CoffeeScript 1.3.3
(function() {
  var config, google_calendar,
    _this = this;

  config = require('../settings');

  google_calendar = require('../calendar-api.js.coffee');

  exports.list = function(req, res) {
    return res.send("respond with a resource");
  };

  exports.auth = function(req, res) {
    return google_calendar.getAuthUrl(function(url) {
      return res.redirect(url);
    });
  };

  exports.authcallback = function(req, res) {
    return google_calendar.getOAuthToken(req.query.code, function(auth_token) {
      req.session.auth_token = auth_token;
      return res.redirect('/');
    });
  };

}).call(this);
